# Libraries made in order so that interdepancies are taken into account
#
default:
	(cd ./libUtils ; make ; cd ../libEigenSolver ; make ; cd ../libLocalStability ; make)

clean:
	(cd ./libUtils ; make clean ; cd ../libEigenSolver ; make clean ; cd ../libLocalStability ; make clean)

